config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_i3:
    dst: ~/.config/i3
    src: config/i3
  f_bashrc:
    dst: ~/.bashrc
    src: bashrc
  f_polybar_config:
    dst: ~/.config/polybar/config
    src: config/polybar/config
  f_run_polybar.sh:
    dst: ~/.run_polybar.sh
    src: run_polybar.sh
  f_vimrc:
    dst: ~/.vimrc
    src: vimrc
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
profiles:
  andros-archbox:
    dotfiles:
    - f_vimrc
    - f_bashrc
    - f_xinitrc
    - d_i3
    - f_polybar_config
    - f_run_polybar.sh
